### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by Hanmo-Tiger** [luckystarufo/MrCAE#1]
Hi Yuying,

Hi! Recently, I was particularly interested in some of your researches, but I encountered difficulties when I wanted to reproduce them. It seems like the .npy data of your notebook programs (sst.mnmean.mask.npy, toy1.npy, toy2.npy, etc.) and some files(data, result, model, npy, etc. )are missing. How / Where could I get them? Hope to get your reply, my email is wza1281365141@163.com.

Many thanks. 
Zian Wang

**Comment by luckystarufo** [comment]
Hi Zian, because the input/model files are too large, they are not uploaded here. You can create empty result/ and model/ folders after forking the repo and run the scripts to generate those files. 

The only missing part that may matter here are the input data (as you said, toy1.npy, toy2.npy, fluid.npy, sst.mnmean.mask.npy, etc. as you mentioned). For toy1.npy and toy2.npy, they are just simulated time series generated using the 'Simulation' part in MrCAE_toy1.ipynb and MrCAE_toy2.ipynb. The 127x127x500 tensors were saved to '../data/npy/'. For the isotropic flow and channel flow example, I have provided the code for querying data from JHU fluid database (http://turbulence.pha.jhu.edu), however, you need to be authorized your own token to get access to it (i.e. contact those guys who own the data, I am not allowed to send the data myself). For the sea surface temperature data, they are available here: https://www.ospo.noaa.gov/Products/ocean/sst/contour/. The website doesn't look the same when I download the data from them ... but I suppose the data source should be the same. Basically what I did was download the data and convert it into a .npy file, no preprocessing was applied. Hopefully the comment is helpful.

**Comment by gauharbains** [comment]
Hey,

I'm also running into an issue while running the notebooks. For both `MrCAE_toy1.ipynb` and `MrCAE_toy2.ipynb`,I saved the data using `np.save('../data/npy/toy2.npy',Phi)`, but I run into the following error in the second cell under MrCAE. Any help would be appreciated, thanks!
```
    627         max_pos_set = set()
    628     else:
--> 629         with open(os.path.join(result_path, 'val_errs.dat'), "rb") as f:
    630             full_val_errs = pickle.load(f)
    631         with open(os.path.join(result_path, 'best_errs.dat'), "rb") as f:

FileNotFoundError: [Errno 2] No such file or directory: '../result/toy2/val_errs.dat'
```

**Comment by luckystarufo** [comment]
Hi Gauhar, before running the script, please create the folder structures. 
For example, if you run MrCAE_toy1.ipynb, please create model/toy1/ and result/toy1/ before proceed.
I had them locally ... but since Github doesn't allow me to upload big files, they disappear for that reason. 

From the error message you pasted, I can see the script is running the 'else' condition here, meaning the variables 'load_model' and 'result_path' are both not None, which further means you are not at the 'base' level and the file 'val_errs.dat' should already exist (more specifically, this file should be generated from the last stage of training).

**Comment by gauharbains** [comment]
I really appreciate your prompt response. I did create the folder structures. I looked through your code and it looks like that the else condition would always execute if I provide `result_path` as input. Even if I don't provide result_path as input, I run into a different error. 
Thank you for your time.

**Comment by luckystarufo** [comment]
Hi Gauhar, I notice that my local code base is not exactly the same as the one in the repo, let me check if I have accidentally pushed the wrong version of the implementation. Meanwhile, let's keep this issue open ... will get back to you a bit later.

**Comment by luckystarufo** [comment]
Hi Gauhar, I confirmed that the code was indeed different and I've updated the file torch_cae_multilevel_V4.py in the src/ folder. After the modification I tried running MrCAE_toy1.ipynb and it worked on my side. Please give it a try. 

Also another point to note, when you save the data, please save the Phi.T instead of Phi. 
i.e. using:   np.save('../data/npy/toy1.npy', scaled_Phi.T)

because for the dateset object, the first dimension is supposed to be the time and the others are spatial dimensions.

**Comment by gauharbains** [comment]
Thank you for updating your codebase. I was able to run `MrCAE_toy1.ipynb`. I'll reach out if I run into any other issues. Appreciate your help!
